[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "obs-nickel"
version = "0.1.0"
description = "LSST obs package for the Nickel telescope"
authors = [{ name = "Dan Gause" }]
dependencies = [
    "astro_metadata_translator>=0.11.0",
    "astropy"
]

[tool.setuptools]
packages = { find = { where = ["python"] } }

[project.entry-points."astro_metadata_translator.translators"]
Nickel = "lsst.obs.nickel.translator:NickelTranslator"
